# Generated by Django 2.2.5 on 2019-11-11 01:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist_A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discoverydate', models.DateField(help_text='※必須', verbose_name='発見日')),
                ('discoverydiv', models.CharField(choices=[('単体テスト', '単体テスト'), ('総合テスト', '総合テスト'), ('その他', 'その他')], help_text='※必須', max_length=20, verbose_name='発見カテゴリ')),
                ('actual_file', models.FileField(blank=True, help_text='※任意', null=True, upload_to='uploaded_files/', verbose_name='添付ファイル')),
                ('severity', models.CharField(choices=[('重度', '重度'), ('軽度', '軽度'), ('正常', '正常')], help_text='※必須', max_length=20, verbose_name='重大度')),
                ('overview', models.TextField(help_text='※必須', verbose_name='発見概要')),
                ('content', models.TextField(help_text='※必須', verbose_name='発見内容')),
                ('actual_file1', models.FileField(blank=True, help_text='※任意', null=True, upload_to='uploaded_files/', verbose_name='添付ファイル１')),
                ('actual_file2', models.FileField(blank=True, help_text='※任意', null=True, upload_to='uploaded_files/', verbose_name='添付ファイル２')),
                ('Image_file1', models.ImageField(blank=True, help_text='※任意', null=True, upload_to='uploaded_files/', verbose_name='イメージファイル１')),
                ('Image_file2', models.ImageField(blank=True, help_text='※任意', null=True, upload_to='uploaded_files/', verbose_name='イメージファイル２')),
                ('causediv', models.CharField(blank=True, choices=[('仕様ミス', '仕様ミス'), ('ハード設計ミス', 'ハード設計ミス'), ('ソフト設計ミス', 'ソフト設計ミス'), ('仕様変更', '仕様変更'), ('その他', 'その他')], max_length=20, null=True, verbose_name='原因区分')),
                ('cause', models.TextField(blank=True, default='', verbose_name='詳細原因')),
                ('actual_file3', models.FileField(blank=True, help_text='※任意', null=True, upload_to='uploaded_files/', verbose_name='添付ファイル３')),
                ('actual_file4', models.FileField(blank=True, help_text='※任意', null=True, upload_to='uploaded_files/', verbose_name='添付ファイル４')),
                ('Image_file3', models.ImageField(blank=True, help_text='※任意', null=True, upload_to='uploaded_files/', verbose_name='イメージファイル３')),
                ('Image_file4', models.ImageField(blank=True, help_text='※任意', null=True, upload_to='uploaded_files/', verbose_name='イメージファイル４')),
                ('counterplan', models.TextField(blank=True, default='', verbose_name='処置内容(対策)')),
                ('actual_file5', models.FileField(blank=True, help_text='※任意', null=True, upload_to='uploaded_files/', verbose_name='添付ファイル５')),
                ('Image_file5', models.ImageField(blank=True, help_text='※任意', null=True, upload_to='uploaded_files/', verbose_name='イメージファイル５')),
                ('completiondate', models.DateField(blank=True, null=True, verbose_name='完了日')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('category', models.ForeignKey(help_text='※必須', on_delete=django.db.models.deletion.PROTECT, to='posts.Category', verbose_name='大分類')),
                ('checklist', models.ManyToManyField(blank=True, to='posts.Checklist_A', verbose_name='チェックリスト')),
                ('equipment', models.ForeignKey(help_text='※必須', on_delete=django.db.models.deletion.PROTECT, to='posts.Equipment', verbose_name='機種名称')),
                ('state', models.ForeignKey(help_text='※必須', on_delete=django.db.models.deletion.PROTECT, to='posts.State', verbose_name='状態')),
                ('subcategory', models.ForeignKey(help_text='※必須', on_delete=django.db.models.deletion.PROTECT, to='posts.Subcategory', verbose_name='小分類')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_image', models.ImageField(upload_to='uploaded_files/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_file', models.FileField(upload_to='uploaded_files/')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='posts.Post')),
            ],
        ),
    ]
