# Generated by Django 2.2.5 on 2019-12-02 08:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Causediv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Checklist_A',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discoverydiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='装置名称')),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Severity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subcategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='小区分')),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discoverydate', models.DateField(help_text='※必須', verbose_name='発見日')),
                ('overview', models.TextField(help_text='※必須', verbose_name='発見概要')),
                ('content', models.TextField(help_text='※必須', verbose_name='発見内容')),
                ('cause', models.TextField(blank=True, default='', verbose_name='詳細原因')),
                ('counterplan', models.TextField(blank=True, default='', verbose_name='処置内容(対策)')),
                ('evidence', models.TextField(blank=True, default='', help_text='（チェックリストのエビデンス登録）', verbose_name='エビデンス')),
                ('url_link', models.URLField(blank=True, help_text='※任意', null=True, verbose_name='URLリンク')),
                ('file_link', models.CharField(blank=True, help_text='※任意', max_length=512, null=True, verbose_name='ファイルサーバーPATH')),
                ('completiondate', models.DateField(blank=True, null=True, verbose_name='完了日')),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('is_public', models.BooleanField(default=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('category', models.ForeignKey(help_text='※必須', on_delete=django.db.models.deletion.PROTECT, to='posts.Category', verbose_name='大分類')),
                ('causediv', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.Causediv', verbose_name='原因区分')),
                ('checklist', models.ManyToManyField(blank=True, to='posts.Checklist_A', verbose_name='チェックリスト')),
                ('discoverydiv', models.ForeignKey(help_text='※必須', on_delete=django.db.models.deletion.PROTECT, to='posts.Discoverydiv', verbose_name='発見カテゴリ')),
                ('equipment', models.ForeignKey(help_text='※必須', on_delete=django.db.models.deletion.PROTECT, to='posts.Equipment', verbose_name='機種名称')),
                ('severity', models.ForeignKey(help_text='※必須', on_delete=django.db.models.deletion.PROTECT, to='posts.Severity', verbose_name='重大度')),
                ('state', models.ForeignKey(help_text='※必須', on_delete=django.db.models.deletion.PROTECT, to='posts.State', verbose_name='状態')),
                ('subcategory', models.ForeignKey(help_text='※必須', on_delete=django.db.models.deletion.PROTECT, to='posts.Subcategory', verbose_name='小分類')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ContentImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_image', models.ImageField(upload_to='', verbose_name='画像ファイル')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
        migrations.CreateModel(
            name='ContentFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_file', models.FileField(upload_to='', verbose_name='添付ファイル')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
    ]
