# Generated by Django 2.2.5 on 2019-11-11 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='Image_file1',
            field=models.ImageField(blank=True, help_text='※任意', null=True, upload_to='uploaded_files', verbose_name='イメージファイル１'),
        ),
    ]
