# Generated by Django 2.2.5 on 2019-12-23 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('is_publick', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Factordiv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='post',
            name='file_link',
            field=models.CharField(blank=True, help_text='※任意\u3000パスの存在はチェックしていません。正しいパスを入力してください。', max_length=512, null=True, verbose_name='関連資料の置き場（共有ファイルサーバーのパス）'),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('text', models.TextField()),
                ('is_public', models.BooleanField(default=False)),
                ('target', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='MarketSpillover',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, default='', verbose_name='理由')),
                ('shippingdate_start', models.DateField(blank=True, null=True, verbose_name='対象品出荷開始日')),
                ('shippingdate_end', models.DateField(blank=True, null=True, verbose_name='対象品出荷終了日')),
                ('shipping', models.CharField(blank=True, max_length=255, null=True, verbose_name='出荷先')),
                ('serial_start', models.CharField(blank=True, max_length=255, null=True, verbose_name='対象製造番号開始')),
                ('serial_end', models.CharField(blank=True, max_length=255, null=True, verbose_name='対象製造番号終了')),
                ('TargetNo', models.CharField(blank=True, max_length=255, null=True, verbose_name='対象台数')),
                ('influence', models.TextField(blank=True, default='', verbose_name='他モデルへの影響')),
                ('factordiv', models.ForeignKey(blank=True, help_text='※「その他」を選択した場合、その要因の内容を理由の欄に記入すること', null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.Factordiv', verbose_name='要因')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post')),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='target',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posts.Post'),
        ),
    ]
