# Generated by Django 2.2.5 on 2019-12-25 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191223_1633'),
    ]

    operations = [
        migrations.RenameField(
            model_name='marketspillover',
            old_name='TargetNo',
            new_name='targetno',
        ),
        migrations.RemoveField(
            model_name='post',
            name='published_date',
        ),
        migrations.AlterField(
            model_name='marketspillover',
            name='factordiv',
            field=models.ForeignKey(blank=True, help_text='※「その他」を選択した場合、その内容を理由の欄に記入してください。', null=True, on_delete=django.db.models.deletion.PROTECT, to='posts.Factordiv', verbose_name='要因'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
