# Generated by Django 2.2.5 on 2019-12-27 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_published_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketspillover',
            name='influence',
            field=models.TextField(blank=True, default='', verbose_name='他機種への影響'),
        ),
        migrations.AlterField(
            model_name='marketspillover',
            name='shippingdate_end',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='対象品出荷終了日'),
        ),
        migrations.AlterField(
            model_name='marketspillover',
            name='shippingdate_start',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='対象品出荷開始日'),
        ),
    ]
