# Generated by Django 2.2.5 on 2019-11-11 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_post_url_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_link',
            field=models.FilePathField(blank=True, help_text='※任意', null=True, verbose_name='ファイルサーバーPATH'),
        ),
    ]
