# Generated by Django 2.2.5 on 2019-12-27 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20191227_1352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketspillover',
            name='factordiv',
        ),
        migrations.AddField(
            model_name='marketspillover',
            name='factor',
            field=models.CharField(blank=True, help_text='(「作業者」、「部品」、「設計」、「設備」、「作業指導」等)', max_length=25, null=True, verbose_name='要因'),
        ),
    ]
