# Generated by Django 2.2.5 on 2019-11-11 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20191111_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='file_link',
        ),
    ]
