# Generated by Django 2.2.5 on 2020-01-06 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20191227_1427'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='completiondate',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='完了日'),
        ),
        migrations.AlterField(
            model_name='post',
            name='discoverydate',
            field=models.CharField(blank=True, help_text='※必須', max_length=10, null=True, verbose_name='発見日'),
        ),
    ]
