# Generated by Django 2.2.5 on 2019-11-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_remove_post_file_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='file_link',
            field=models.CharField(blank=True, help_text='※任意', max_length=512, null=True, verbose_name='ファイルサーバーPATH'),
        ),
    ]
