# Generated by Django 2.2.5 on 2019-11-14 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_auto_20191112_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Image_file1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Image_file2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Image_file3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Image_file4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='Image_file5',
        ),
        migrations.RemoveField(
            model_name='post',
            name='actual_file',
        ),
        migrations.RemoveField(
            model_name='post',
            name='actual_file1',
        ),
        migrations.RemoveField(
            model_name='post',
            name='actual_file2',
        ),
        migrations.RemoveField(
            model_name='post',
            name='actual_file3',
        ),
        migrations.RemoveField(
            model_name='post',
            name='actual_file4',
        ),
        migrations.RemoveField(
            model_name='post',
            name='actual_file5',
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='content_file',
            field=models.FileField(upload_to='uploaded_files/', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='content_image',
            field=models.ImageField(upload_to='uploaded_files/', verbose_name='画像ファイル'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=255, verbose_name='装置名称'),
        ),
        migrations.AlterField(
            model_name='subcategory',
            name='name',
            field=models.CharField(max_length=255, verbose_name='小区分'),
        ),
    ]
