# Generated by Django 2.2.5 on 2019-11-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0012_auto_20191120_0942'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contentfile',
            name='file_type',
        ),
        migrations.AlterField(
            model_name='contentfile',
            name='content_file',
            field=models.FileField(upload_to='', verbose_name='添付ファイル'),
        ),
        migrations.AlterField(
            model_name='contentimage',
            name='content_image',
            field=models.ImageField(upload_to='', verbose_name='画像ファイル'),
        ),
    ]
